[energies]
v = 1
dim = [20]
data = [0.0, 10.526315789473685, 21.05263157894737, 31.578947368421055, 42.10526315789474, 52.631578947368425, 63.15789473684211, 73.6842105263158, 84.21052631578948, 94.73684210526316, 105.26315789473685, 115.78947368421053, 126.31578947368422, 136.84210526315792, 147.3684210526316, 157.89473684210526, 168.42105263157896, 178.94736842105266, 189.47368421052633, 200.0]

[angles]
v = 1
dim = [20]
data = [0.0, 4.7368421052631575, 9.473684210526315, 14.210526315789473, 18.94736842105263, 23.684210526315788, 28.421052631578945, 33.1578947368421, 37.89473684210526, 42.63157894736842, 47.368421052631575, 52.10526315789473, 56.84210526315789, 61.57894736842105, 66.3157894736842, 71.05263157894737, 75.78947368421052, 80.52631578947367, 85.26315789473684, 90.0]

[x_range]
v = 1
dim = [50]
data = [0.0, 1.0204081632653061, 2.0408163265306123, 3.0612244897959187, 4.081632653061225, 5.1020408163265305, 6.122448979591837, 7.142857142857143, 8.16326530612245, 9.183673469387756, 10.204081632653061, 11.224489795918368, 12.244897959183675, 13.26530612244898, 14.285714285714286, 15.306122448979592, 16.3265306122449, 17.346938775510203, 18.367346938775512, 19.387755102040817, 20.408163265306122, 21.42857142857143, 22.448979591836736, 23.46938775510204, 24.48979591836735, 25.510204081632654, 26.53061224489796, 27.551020408163264, 28.571428571428573, 29.591836734693878, 30.612244897959183, 31.63265306122449, 32.6530612244898, 33.673469387755105, 34.69387755102041, 35.714285714285715, 36.734693877551024, 37.755102040816325, 38.775510204081634, 39.79591836734694, 40.816326530612244, 41.83673469387755, 42.85714285714286, 43.87755102040816, 44.89795918367347, 45.91836734693878, 46.93877551020408, 47.95918367346939, 48.9795918367347, 50.0]

[y_range]
v = 1
dim = [20]
data = [-30.0, -24.210526315789473, -18.421052631578945, -12.631578947368421, -6.842105263157894, -1.0526315789473664, 4.7368421052631575, 10.526315789473685, 16.315789473684212, 22.10526315789474, 27.894736842105267, 33.684210526315795, 39.473684210526315, 45.26315789473685, 51.05263157894737, 56.842105263157904, 62.631578947368425, 68.42105263157895, 74.21052631578948, 80.0]

[z_range]
v = 1
dim = [20]
data = [-0.1, -0.08947368421052632, -0.07894736842105264, -0.06842105263157895, -0.05789473684210527, -0.04736842105263159, -0.0368421052631579, -0.026315789473684223, -0.015789473684210534, -0.005263157894736845, 0.005263157894736831, 0.01578947368421052, 0.02631578947368421, 0.0368421052631579, 0.04736842105263156, 0.05789473684210525, 0.06842105263157894, 0.07894736842105263, 0.08947368421052632, 0.09999999999999998]

[reflected_ead]
v = 1
dim = [20, 20]
data = [0, 9, 6, 9, 9, 15, 12, 13, 16, 10, 8, 9, 7, 8, 3, 1, 1, 0, 0, 0, 0, 3, 6, 11, 6, 2, 10, 10, 10, 13, 14, 7, 6, 8, 4, 1, 1, 0, 0, 0, 0, 2, 1, 4, 1, 6, 4, 4, 7, 4, 6, 4, 3, 6, 2, 1, 1, 0, 0, 0, 0, 0, 2, 1, 1, 1, 4, 1, 7, 9, 5, 5, 4, 1, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1, 1, 2, 1, 0, 2, 3, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 4, 0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[sputtered_ead]
v = 1
dim = [20, 20]
data = [3, 1, 3, 5, 5, 3, 6, 5, 7, 7, 4, 4, 6, 4, 4, 2, 3, 3, 1, 0, 0, 0, 0, 0, 1, 1, 2, 2, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[implanted_x]
v = 1
dim = [50]
data = [1, 11, 13, 32, 31, 32, 31, 33, 27, 34, 36, 36, 34, 20, 26, 19, 18, 19, 13, 17, 19, 10, 15, 14, 13, 7, 10, 6, 4, 4, 3, 4, 2, 3, 0, 1, 4, 3, 1, 0, 3, 0, 1, 2, 1, 1, 0, 1, 0, 0]

[implanted_y]
v = 1
dim = [20]
data = [0, 1, 6, 13, 17, 37, 59, 68, 66, 82, 48, 60, 75, 38, 26, 17, 3, 1, 0, 0]

[implanted_z]
v = 1
dim = [20]
data = [0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]

[electronic_energy_loss_x]
v = 1
dim = [50]
data = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[nuclear_energy_loss_x]
v = 1
dim = [50]
data = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

